name: hola-mundo
run-name: 'I am learning github actions'
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
      - name: Run the script
        run: node ../app.js
