name: Learning Github Actions
run-name: ¡I'm learning Github Actions!
on: [push]
jobs:
  hola-mundo:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.0

    - name: run script
      run: node helloWorld.js